"""add_supported_models_to_machines

Revision ID: 0ddbf4f95feb
Revises: 7f3f85959d24
Create Date: 2025-08-22 01:15:56.391862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0ddbf4f95feb'
down_revision: Union[str, None] = '7f3f85959d24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machine', sa.Column('supported_models', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machine', 'supported_models')
    # ### end Alembic commands ###
