"""auto credit

Revision ID: 2337eba1ff88
Revises: 7a5160124373
Create Date: 2025-02-03 16:40:18.219089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2337eba1ff88'
down_revision: Union[str, None] = '7a5160124373'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('auto_credit', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'auto_credit')
    # ### end Alembic commands ###
