"""ttfs to ApiLog

Revision ID: 3182b5f9abe0
Revises: daafefc85a9b
Create Date: 2025-01-10 16:23:28.782876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3182b5f9abe0'
down_revision: Union[str, None] = 'daafefc85a9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apilogs', sa.Column('ttft', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apilogs', 'ttft')
    # ### end Alembic commands ###
