"""add variables list

Revision ID: 3754158bba54
Revises: 3182b5f9abe0
Create Date: 2025-01-11 14:18:44.663927

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3754158bba54"
down_revision: Union[str, None] = "3182b5f9abe0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("flows", sa.Column("variables", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("flows", "variables")
    # ### end Alembic commands ###
