"""handle machine tokens

Revision ID: 62e3abf11bf8
Revises: 9546f6a628e7
Create Date: 2025-02-14 14:26:22.170381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62e3abf11bf8'
down_revision: Union[str, None] = '9546f6a628e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machinetoken',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('api_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machinetoken_api_token'), 'machinetoken', ['api_token'], unique=True)
    op.create_index(op.f('ix_machinetoken_machine_id'), 'machinetoken', ['machine_id'], unique=False)
    op.drop_column('machine', 'auth_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machine', sa.Column('auth_tokens', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_machinetoken_machine_id'), table_name='machinetoken')
    op.drop_index(op.f('ix_machinetoken_api_token'), table_name='machinetoken')
    op.drop_table('machinetoken')
    # ### end Alembic commands ###
