"""add index to usercredithistory

Revision ID: 71fb79bd3089
Revises: 493837a3f007
Create Date: 2025-02-22 13:17:48.614431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '71fb79bd3089'
down_revision: Union[str, None] = '493837a3f007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_usercreditshistory_user_id'), 'usercreditshistory', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usercreditshistory_user_id'), table_name='usercreditshistory')
    # ### end Alembic commands ###
