"""add traffic weight

Revision ID: 7f3f85959d24
Revises: 828ec7299bbd
Create Date: 2025-08-22 00:14:23.342690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7f3f85959d24'
down_revision: Union[str, None] = '828ec7299bbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machine', sa.Column('traffic_weight', sa.Float(), server_default='0.5', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machine', 'traffic_weight')
    # ### end Alembic commands ###
