"""auto credit system

Revision ID: 9124da4a1c30
Revises: b40096408f78
Create Date: 2025-02-03 13:40:36.894953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9124da4a1c30'
down_revision: Union[str, None] = 'b40096408f78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('auto_credit', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'auto_credit')
    # ### end Alembic commands ###
