"""drop machine uid

Revision ID: 9546f6a628e7
Revises: bbe0e549299d
Create Date: 2025-02-14 12:35:16.688438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9546f6a628e7'
down_revision: Union[str, None] = 'bbe0e549299d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_machine_network_machine_uid', table_name='machine')
    op.drop_column('machine', 'network_machine_uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machine', sa.Column('network_machine_uid', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_machine_network_machine_uid', 'machine', ['network_machine_uid'], unique=True)
    # ### end Alembic commands ###
