"""wallet user_id relation fix

Revision ID: 9d6c46c7776e
Revises: 41f46405db51
Create Date: 2025-02-02 19:43:33.454695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9d6c46c7776e'
down_revision: Union[str, None] = '41f46405db51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('wallet_user_id_fkey', 'wallet', type_='foreignkey')
    
    # Convert user_id to UUID type
    op.execute('ALTER TABLE wallet ALTER COLUMN user_id TYPE UUID USING user_id::uuid')
    
    # Create the foreign key with matching UUID types
    op.create_foreign_key(None, 'wallet', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallet', type_='foreignkey')
    
    # Convert back to VARCHAR
    op.alter_column('wallet', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    
    op.create_foreign_key('wallet_user_id_fkey', 'wallet', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
