"""add fields to machine

Revision ID: a216eb44cd59
Revises: b444557df1e6
Create Date: 2025-01-17 18:40:24.771794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a216eb44cd59'
down_revision: Union[str, None] = 'b444557df1e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machine', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('machine', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('machine', sa.Column('auth_tokens', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('machine', sa.Column('disabled', sa.BOOLEAN(), server_default='False', nullable=False))
    op.drop_index('ix_machine_network_ip', table_name='machine')
    op.create_index(op.f('ix_machine_network_ip'), 'machine', ['network_ip'], unique=True)
    op.drop_index('ix_machine_network_machine_uid', table_name='machine')
    op.create_index(op.f('ix_machine_network_machine_uid'), 'machine', ['network_machine_uid'], unique=True)
    op.create_index(op.f('ix_machine_description'), 'machine', ['description'], unique=False)
    op.create_index(op.f('ix_machine_name'), 'machine', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_machine_name'), table_name='machine')
    op.drop_index(op.f('ix_machine_description'), table_name='machine')
    op.drop_index(op.f('ix_machine_network_machine_uid'), table_name='machine')
    op.create_index('ix_machine_network_machine_uid', 'machine', ['network_machine_uid'], unique=False)
    op.drop_index(op.f('ix_machine_network_ip'), table_name='machine')
    op.create_index('ix_machine_network_ip', 'machine', ['network_ip'], unique=False)
    op.drop_column('machine', 'disabled')
    op.drop_column('machine', 'auth_tokens')
    op.drop_column('machine', 'description')
    op.drop_column('machine', 'name')
    # ### end Alembic commands ###
