"""wallet table fix

Revision ID: a2f9d39fbdb5
Revises: f7b3074be5ba
Create Date: 2025-02-02 19:27:41.214854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a2f9d39fbdb5'
down_revision: Union[str, None] = 'f7b3074be5ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE wallet ALTER COLUMN id TYPE UUID USING id::uuid')
    op.create_foreign_key(None, 'wallet', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallet', type_='foreignkey')
    op.alter_column('wallet', 'id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
