"""api-key-id in api-logs table

Revision ID: bf671128ab6b
Revises: 3754158bba54
Create Date: 2025-01-12 16:26:22.271605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf671128ab6b'
down_revision: Union[str, None] = '3754158bba54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apilogs', sa.Column('api_key_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_apilogs_api_key_id'), 'apilogs', ['api_key_id'], unique=False)
    op.alter_column('usercustomclaim', 'claim',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usercustomclaim', 'claim',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_apilogs_api_key_id'), table_name='apilogs')
    op.drop_column('apilogs', 'api_key_id')
    # ### end Alembic commands ###
