"""ApiLogs model update to support pricing

Revision ID: daafefc85a9b
Revises: b1e9f3d335d7
Create Date: 2025-01-10 14:26:54.944579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'daafefc85a9b'
down_revision: Union[str, None] = 'b1e9f3d335d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apilogs', sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('apilogs', sa.Column('model_pricing', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('apilogs', sa.Column('machine_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('apilogs', 'payload',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_apilogs_machine_id'), 'apilogs', ['machine_id'], unique=False)
    op.create_index(op.f('ix_apilogs_user_id'), 'apilogs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apilogs_user_id'), table_name='apilogs')
    op.drop_index(op.f('ix_apilogs_machine_id'), table_name='apilogs')
    op.alter_column('apilogs', 'payload',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('apilogs', 'machine_id')
    op.drop_column('apilogs', 'model_pricing')
    op.drop_column('apilogs', 'request_payload')
    # ### end Alembic commands ###
