name: SDK Lint

on:
  workflow_call:

jobs:
  sdk-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sdk
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pdm ruff black

      - name: Format with Ruff
        run: pdm format

      - name: Lint with Ruff
        run: pdm lint
