name: Checkout and Install Dependencies

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string

jobs:
  checkout_and_install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn
        working-directory: ${{ inputs.working-directory }}
