name: Create New Relic Deployment Marker

on:
  workflow_call:

jobs:
  create_deployment_marker:
    runs-on: ubuntu-latest
    steps:
      - name: Create New Relic Deployment Marker
        env:
          NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
        run: |
          echo "Creating New Relic Deployment Marker"
          response=$(curl -s -o response.txt -w "%{http_code}" -X POST "https://api.newrelic.com/v2/applications/1120363591/deployments.json" \
          -H "X-Api-Key:${{ secrets.NEW_RELIC_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{
            "deployment": {
              "revision": "${{ github.sha }}",
              "changelog": "Deployed via GitHub Actions",
              "description": "Deployment to production",
              "user": "${{ github.actor }}"
            }
          }')

          if [ "$response" -ne 201 ]; then
            echo "Failed to create New Relic Deployment Marker. HTTP status: $response"
            cat response.txt
          else
            echo "New Relic Deployment Marker created successfully."
          fi
