name: Publish to Cloudflare Pages

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string

jobs:
  publish_to_cloudflare:
    runs-on: ubuntu-latest
    steps:
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: "b9d9855d1fdfcd9fb504dc752c05499f"
          projectName: "console-alts"
          workingDirectory: ${{ inputs.working-directory }}
          directory: out
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
