name: Upload Sourcemaps to New Relic

on: workflow_call

jobs:
  upload_sourcemaps:
    runs-on: ubuntu-latest
    steps:
      - name: Upload Sourcemaps to New Relic
        env:
          NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
        run: |
          node -e "
          const { readdirSync } = require('fs');
          const { join } = require('path');
          const publishSourcemap = require('@newrelic/publish-sourcemap').publishSourcemap;

          const sourcemapDir = join(__dirname, 'out/_next/static');
          try {
            const sourcemapFiles = readdirSync(sourcemapDir, { withFileTypes: true })
              .filter(dirent => dirent.isDirectory())
              .flatMap(dirent => {
                const subDir = join(sourcemapDir, dirent.name);
                return readdirSync(subDir)
                  .filter(file => file.endsWith('.map'))
                  .map(file => join(subDir, file));
              });

            if (sourcemapFiles.length === 0) {
              throw new Error('No sourcemap files found.');
            }

            sourcemapFiles.forEach(sourcemapPath => {
              const javascriptUrl = \`https://console.mira.network\${sourcemapPath.replace('out', '').replace('.map', '')}\`;

              publishSourcemap({
                sourcemapPath,
                javascriptUrl,
                applicationId: 1120363591,
                apiKey: process.env.NEW_RELIC_API_KEY,
              }, function (err) {
                if (err) {
                  console.error(\`Error uploading sourcemap for \${sourcemapPath}: \`, err);
                } else {
                  console.log(\`Source map upload done for \${sourcemapPath}\`);
                }
              });
            });
          } catch (error) {
            console.error('Error processing sourcemaps:', error);
          }
          "
