services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./database.db:/app/database.db
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis/redis-stack:latest
    ports:
      - "8001:8001"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
