services:
  router:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: router
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./database.db:/app/database.db
    ports:
      - "8000:80"
    depends_on:
      - redis

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "8001:8001"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./.v/redis/data:/data
