version: '3'

services:
  inference-logs:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - SIGNER_PRIVATE_KEY=${SIGNER_PRIVATE_KEY}
      - RPC_URL_HTTP=https://rpc-test0-two-zepe2m25hg.t.conduit.xyz
      - RPC_URL_WS=wss://rpc-test0-two-zepe2m25hg.t.conduit.xyz
      - APP_ID=Klok
      - BATCH_SIZE=100
      - PORT=3000
      - HOST=0.0.0.0
    restart: unless-stopped 