version: '3'

services:
  inference-logs:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - SIGNER_PRIVATE_KEY=${SIGNER_PRIVATE_KEY}
      - RPC_URL_HTTP=https://sepolia.base.org
      - RPC_URL_WS=wss://sepolia.base.org
      - APP_ID=Klok
      - BATCH_SIZE=100
      - PORT=3000
      - HOST=0.0.0.0
    restart: unless-stopped 
