name: Prod Deploy to Cloudflare pages

on:
  push:
    branches:
      - main
    paths:
      - "playground_v2/**"
      - ".github/workflows/console-prod-deployment.yaml"

permissions:
  contents: read
  deployments: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./playground_v2
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn
      - name: Build
        env:
          NEXT_PUBLIC_SUPABASE_URL: https://atmocsvasyapsvwsustd.supabase.co
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          NEXT_PUBLIC_API_BASE_URL: https://mira-network.alts.dev
          NEXT_PUBLIC_LLM_BASE_URL: https://mira-network.alts.dev/v1
          NEXT_PUBLIC_URL: https://console.mira.network
          NEW_RELIC_APP_NAME: mira-console
          NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
        run: yarn build

      - name: Upload Sourcemaps to New Relic
        env:
          NEW_RELIC_API_KEY: NRBR-af69bcb8e4875e9c1f6
        run: |
          node -e "
          const { readdirSync } = require('fs');
          const { join } = require('path');
          const publishSourcemap = require('@newrelic/publish-sourcemap').publishSourcemap;

          const sourcemapDir = join(__dirname, 'out/_next/static');
          const sourcemapFiles = readdirSync(sourcemapDir, { withFileTypes: true })
            .filter(dirent => dirent.isDirectory())
            .flatMap(dirent => {
              const subDir = join(sourcemapDir, dirent.name);
              return readdirSync(subDir)
                .filter(file => file.endsWith('.map'))
                .map(file => join(subDir, file));
            });

          console.log('sourcemapDir=', sourcemapDir);
          console.log('sourcemapFiles=', sourcemapFiles);
          console.log('NEW_RELIC_API_KEY=', process.env.NEW_RELIC_API_KEY);

          sourcemapFiles.forEach(sourcemapPath => {
            const javascriptUrl = \`https://console.mira.network\${sourcemapPath.replace('out', '').replace('.map', '')}\`;

            publishSourcemap({
              sourcemapPath,
              javascriptUrl,
              applicationId: 1120363591,
              apiKey: 'NRBR-af69bcb8e4875e9c1f6',
            }, function (err) {
              console.log(err || \`Source map upload done for \${sourcemapPath}\`);
            });
          });
          "

      - name: Create New Relic Deployment Marker
        run: |
          echo "Creating New Relic Deployment Marker"
          curl -v -X POST "https://api.newrelic.com/v2/applications/1120363591/deployments.json" \
          -H "X-Api-Key:NRBR-af69bcb8e4875e9c1f6" \
          -H "Content-Type: application/json" \
          -d '{
            "deployment": {
              "revision": "${{ github.sha }}",
              "changelog": "Deployed via GitHub Actions",
              "description": "Deployment to production",
              "user": "${{ github.actor }}"
            }
          }'

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: "b9d9855d1fdfcd9fb504dc752c05499f"
          projectName: "console-alts"
          workingDirectory: playground_v2
          directory: out
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
