name: Prod Deploy to Cloudflare pages

on:
  push:
    branches:
      - main
    paths:
      - "playground_v2/**"
      - ".github/workflows/console-prod-deployment.yaml"

permissions:
  contents: read
  deployments: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./playground_v2
    steps:
      - name: Checkout and Install
        uses: ./.github/workflows/steps/checkout-and-install.yml

      - name: Build
        uses: ./.github/workflows/steps/build.yml

      - name: Upload Sourcemaps
        uses: ./.github/workflows/steps/upload-sourcemaps.yml

      - name: Create Deployment Marker
        uses: ./.github/workflows/steps/create-deployment-marker.yml

      - name: Publish to Cloudflare
        uses: ./.github/workflows/steps/publish-to-cloudflare.yml
