name: PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41

      - name: Get PR diff
        id: pr-diff
        run: |
          git diff --unified=3 ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} > pr.diff

      - name: Review PR
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const https = require('https');
            const diff = fs.readFileSync('pr.diff', 'utf8');

            // Function to make OpenAI API request
            async function callOpenAI(messages) {
              return new Promise((resolve, reject) => {
                const data = JSON.stringify({
                  model: "gpt-4",
                  messages: messages,
                  temperature: 0.7,
                  max_tokens: 2048
                });

                const options = {
                  hostname: 'api.openai.com',
                  path: '/v1/chat/completions',
                  method: 'POST',
                  headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${process.env.OPENAI_API_KEY}`,
                  }
                };

                const req = https.request(options, (res) => {
                  let responseData = '';
                  res.on('data', (chunk) => { responseData += chunk; });
                  res.on('end', () => {
                    try {
                      const parsedData = JSON.parse(responseData);
                      if (parsedData.error) {
                        reject(new Error(parsedData.error.message));
                      } else {
                        resolve(parsedData.choices[0].message.content);
                      }
                    } catch (error) {
                      reject(error);
                    }
                  });
                });

                req.on('error', (error) => {
                  reject(error);
                });

                req.write(data);
                req.end();
              });
            }

            const prompt = `Review the following pull request changes and provide concise feedback:

            ${diff}

            Provide:
            1. Brief summary of changes
            2. Key concerns (if any)
            3. Suggestions
            4. Code quality rating (1-5)`;

            const messages = [
              { role: "system", content: "You are a concise code reviewer. Focus on the most important aspects." },
              { role: "user", content: prompt }
            ];

            try {
              const review = await callOpenAI(messages);

              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: review
              });
            } catch (error) {
              core.setFailed(`Error during PR review: ${error.message}`);
            }
