name: Publish Router

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  publish-router:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      VERSION: ${{ inputs.version }}
      REGISTRY: ghcr.io
      ROUTER_IMAGE: Aroha-Labs/mira-client-router
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Router
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.ROUTER_IMAGE }}
          tags: |
            type=ref,event=branch
            type=sha,prefix=,format=short
            type=raw,value=latest
            type=raw,value=${{ env.VERSION }}

      - name: Build and push Router image
        uses: docker/build-push-action@v6
        with:
          context: router
          build-args: |
            IMAGE_VERSION=${{ env.VERSION }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Clean up Docker images
        run: docker image prune -f
