name: Create Tags and Publish Images

on:
  push:
    branches: ["main", "develop"]
    paths:
      - "router/**"
      - "playground/**"
      - "service/**"
      - "cli/**"
      - "sdk/**"
      - ".github/workflows/release.yml"

env:
  REGISTRY: ghcr.io
  ROUTER_IMAGE: Aroha-Labs/mira-client-router
  SERVICE_IMAGE: Aroha-Labs/mira-client-service

permissions:
  contents: write
  deployments: write
  packages: write
  pull-requests: write

jobs:
  changes:
    uses: ./.github/workflows/changes.yml

  create-tag:
    needs: changes
    uses: ./.github/workflows/create-tag.yml
    if: |
      needs.changes.outputs.router == 'true' ||
      needs.changes.outputs.service == 'true' ||
      needs.changes.outputs.cli == 'true' ||
      needs.changes.outputs.playground == 'true' ||
      needs.changes.outputs.sdk == 'true'

  publish-router:
    needs: [changes, create-tag]
    if: needs.changes.outputs.router == 'true'
    uses: ./.github/workflows/publish-router.yml
    with:
      version: ${{ needs.create-tag.outputs.new_tag }}

  publish-service:
    needs: [changes, create-tag]
    if: needs.changes.outputs.service == 'true'
    uses: ./.github/workflows/publish-service.yml
    with:
      version: ${{ needs.create-tag.outputs.new_tag }}

  publish-cli:
    needs: [changes, create-tag]
    uses: ./.github/workflows/publish-cli.yml
    with:
      version: ${{ needs.create-tag.outputs.new_tag }}

  deploy-console-testnet:
    needs: [changes, create-tag]
    if: needs.changes.outputs.playground == 'true'
    uses: ./.github/workflows/deploy-console-testnet.yml
    with:
      version: ${{ needs.create-tag.outputs.new_tag }}

  sdk-test:
    needs: [changes, create-tag]
    if: needs.changes.outputs.sdk == 'true'
    uses: ./.github/workflows/sdk-test.yml

  sdk-lint:
    needs: [changes, create-tag]
    if: needs.changes.outputs.sdk == 'true'
    uses: ./.github/workflows/sdk-lint.yml

  sonarqube:
    needs: [changes, create-tag]
    if: needs.changes.outputs.sdk == 'true'
    uses: ./.github/workflows/sonarqube.yml

  summary:
    needs:
      [
        changes,
        create-tag,
        publish-router,
        publish-service,
        publish-cli,
        deploy-console-testnet,
        sdk-test,
        sdk-lint,
      ]
    if: always()
    uses: ./.github/workflows/summary.yml
    with:
      new_tag: ${{ needs.create-tag.outputs.new_tag }}
      router_result: ${{ needs.publish-router.result }}
      service_result: ${{ needs.publish-service.result }}
      cli_result: ${{ needs.publish-cli.result }}
      playground_result: ${{ needs.deploy-console-testnet.result }}
      sdk_test_result: ${{ needs.sdk-test.result }}
      sdk_lint_result: ${{ needs.sdk-lint.result }}
